version: "3.9"

services:
  mysqldb:
    container_name: mysqldb-transaction
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: transaction_demo
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    volumes:
      - transaction_volume:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - springboot-mysql-net

volumes:
  transaction_volume:

networks:
    springboot-mysql-net:
        driver: bridge


